extern void __VERIFIER_error() __attribute__ ((__noreturn__));

/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void __assert_fail(char const   *__assertion ,
                                                                      char const   *__file ,
                                                                      unsigned int __line ,
                                                                      char const   *__function ) ;

int CURRENTLY_UNSAFE  ;
int main(void) 
{ int a ;
  int b ;
  int *p1 ;
  int *p2 ;
  int *__cil_tmp5 ;
  unsigned int __cil_tmp6 ;
  unsigned int __cil_tmp7 ;
  int *__cil_tmp8 ;
  unsigned int __cil_tmp9 ;
  unsigned int __cil_tmp10 ;
  unsigned int __cil_tmp11 ;
  unsigned int __cil_tmp12 ;

  {
  p1 = & a;
  p2 = & b;
  {
  __cil_tmp5 = (int *)0;
  __cil_tmp6 = (unsigned int )__cil_tmp5;
  __cil_tmp7 = (unsigned int )p1;
  if (__cil_tmp7 != __cil_tmp6) {
    {
    __cil_tmp8 = (int *)0;
    __cil_tmp9 = (unsigned int )__cil_tmp8;
    __cil_tmp10 = (unsigned int )p2;
    if (__cil_tmp10 != __cil_tmp9) {
      {
      __cil_tmp11 = (unsigned int )p2;
      __cil_tmp12 = (unsigned int )p1;
      if (__cil_tmp12 != __cil_tmp11) {

      } else {
        {
        //__assert_fail("p1!=p2", "test_malloc-2-safe.c", 28U, "main");
        ERROR: __VERIFIER_error();
        }
      }
      }
    } else {

    }
    }
  } else {

  }
  }
  return (0);
}
}
